from dataclasses import dataclass


@dataclass
class Constants:
    NUM_LETTERS_IN_ALPHABET = 26
    ASCII_UPPER_CASE_LETTER_START = 65
    ASCII_UPPER_CASE_LETTER_END = 90
    ASCII_LOWER_CASE_LETTER_START = 97
    ASCII_LOWER_CASE_LETTER_END = 122
    ASCII_NUMBER_START = 48
    ASCII_NUMBER_END = 57
